### ISSUE TITLE
TX audio garbled

### ISSUE THREAD

**Issue by aknrdureegaesr** [nonoo/kappanhang#8]
Great project! A joy to see it!

On my Debian Buster system, WSJTX RX worked pretty much out of the box, but the output of TX is interrupted and garbled.

I enclose, in the accompanying [kappanhang-sound-problem.zip](https://github.com/nonoo/kappanhang/files/5737396/kappanhang-sound-problem.zip):

* a sound file that was produced with the IC-705's record function,
* the output of `pacmd dump` before `kappanhang` was even started
* the output of `pacmd dump` with `kappanhang` and `wsjtx` both running

FWIW: I run a self-compiled version of `kappanhang`, as the precompiled does not work, with error message

> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./kappanhang_1.2)

73 es gl de Andreas, dj3ei

**Comment by nonoo** [comment]
Your IC705 may have a poor Wi-Fi connection (note that the connection can have issues caused by interference even if the radio displays high signal strength - the IC705 has very limited Wi-Fi hardware). Please see the Icom IC-705 Wi-Fi notes in the user manual.

If you are absolutely sure that the IC705 has a good Wi-Fi connection, then try increasing audio buffers in the source code.
